### ISSUE TITLE
Tester Project

### ISSUE THREAD

**Issue by AditXtreme** [Hirozuto/tester#5]
##Rom
GSI

##Codename
X689

## Devices
INFINIX HOT 10S

Platform: mt6768
Architecture: Arm64
Kernel Version: 4.14
System Partition Size: 4580MB, 4.7GB
Vendor version: VNDK30

## (FOD)
No

## If sometimes we need a logs, can you capture it and send to us?
Yes.

**Comment by hiratazx** [comment]
that's a good detailed information about your device. your form style doesn't matter, at least your device information is detailed
