### ISSUE TITLE
SereMilPano #HanoipSupremacy

### ISSUE THREAD

**Issue by SereMilPano** [Hirozuto/tester#6]
## Which device you want to use for testing
```
Moto G60 Hanoip
```

## Detailed information about your devices
```
Platform: Qualcomm SM7150 732G (8nm)
Architecture:  arm64-v8a (64-bit)
Kernel Version: Linux version 4.14.190-perf+
System Partition Size: ( 3800MB, 3.80GB)
Vendor version: vndk32
```

## Is your device using Fingerprint on Display? (FOD)
```
No.
```

## If sometimes we need a logs, can you capture it and send to us?
```
Yes.
```

### @SereMilPano
```
Your Telegram username
```
Sere <3

**Comment by hiratazx** [comment]
yoo nice, finally a more detailed hardware info
